### ISSUE TITLE
STT0081: STT Nyamrub Data Formatter for Validation and Contribution Preparation

### ISSUE THREAD

**Issue by jim-gyas** [OpenPecha/stt-nyamrub-data-formatter#1]
### Description: 
Creating a formatter for STT Nyamrub data tailored for the Nyamrub website in two distinct formats: 
- for validation purposes
- for contribution purposes.

### Completion Criteria:
- Successfully generate validation and contribution datasets with the specified formats and at least 50,000 rows each, covering all dialects.
- Ensure all rows in the datasets are tagged with difficulty levels using the STT Level Tagger

### Resources:
- Nyamrub Data Format : [Nyamrub Format](https://github.com/OpenPecha/nyamrub-backend/tree/main/database)
- STT Level Tagger : [STT Level Tagger](https://github.com/OpenPecha/stt_level_tagger)

### Validation Format:
```
origin_id,source_audio_url,target,score,source_dialect,source_language,target_language
1,source_audio_url_1,ཕྱི་ལོ་ཉིས་སྟོང་ཉི་ཤུ་རྩ་བཞི་ལོའི་ཟླ་བ་བརྒྱད་པའི་ནང་།,10,khampa,tibetan,tibetan
2,source_audio_url_2,རྒྱ་ནག་གཞུང་གིས་མཚོ་སྔོན་ཞིང་ཆེན་གོ་ལོག་ཁུལ་བཙུགས་ནས་ལོ་འཁོར་བདུན་ཅུ་འཁོ་བའི་མཛད་སྒོ་འཚོགས་ཡོད་པ་བཞིན།,5,U-tsang,tibetan,tibetan
3,source_audio_url_3,ཕྱི་ཟླ་བརྒྱད་པའི་ནང་རྒྱ་ནག་གཞུང་གི་མགོ་ལོག་མངའ་ཁུལ་གྱི་ས་གནས་གང་སར་དམ་བསྒྲགས་ཤུགས་ཆེར་ཆེ་ཡོད་པ་དང་།,15,Amdo,tibetan,tibetan
```
### Contribution Format:
```
origin_id,source_audio_url,target,score,source_dialect,source_language,target_language
1,source_audio_url_1,,10,khampa,tibetan,tibetan
2,source_audio_url_2,,5,U-tsang,tibetan,tibetan
3,source_audio_url_3,,15,Amdo,tibetan,tibetan
```
### Subtasks:
- [x] Generate Contribution Data:
   - [x] Run the make csv script to generate the contribution data without transcripts for three dialects: Khampa, U-tsang (News Catalog), and Amdo.
   - [x] Write a Script to Merge the generated CSV files for Khampa, U-tsang (News Catalog), and Amdo into a single contribution dataset.
   - [x] Ensure at least 50,000 rows in total are created.
- [x]  Extract Validation Data:
   - [x] Use data already in the transcribed state from stt_pecha_tool to prepare the validation dataset.
   - [x] Merge the extracted CSV files for Khampa, U-tsang, and Amdo into a single validation dataset.
   - [x] Ensure at least 50,000 rows in total are included. 
- [x]  Apply the STT Level Tagger to both the contribution and validation datasets to classify audio segments by difficulty level.
- [x]  Write a Python script to format the above data into their respective validation and contribution formats.

#### Reviewer: @gangagyatso4364 
- [x] Reviewed
